### ISSUE TITLE
new release tag request: no fixed (unique) release tag yet

### ISSUE THREAD

**Issue by vowstar** [B-Lang-org/bsc#288]
This may brings problems to many Linux distributions that want to use the unique version of the package.
Could an updated release tag be issued if it is convenient? Thank you!

**Comment by quark17** [comment]
Yes, I agree!  Until a point in the repo is tagged as a particular version (for example BSC v4.0.0), packaging BSC for Unix distros is difficult.  I would also like this GitHub repo to have pre-built tar-files for download, and that can't happen either until we tag a version.

This is discussed in issue #137.  As I said in a [comment](https://github.com/B-Lang-org/bsc/issues/137#issuecomment-613107744_), one thing is holding up the process.

It was suggested that we change the directory layout of the BSC installation, and doing that would be a significant change, and so it was suggested that we do this before making a first release (rather than make such a disruptive change later).  This is issue #85 , where I have also just added a comment, to hopefully move that discussion along.

**Comment by vowstar** [comment]
Thanks for reply! I'm looking forward to the release of the new version.
