### ISSUE TITLE
error: _@%@_  BinData.readShared: invalid tag 95

### ISSUE THREAD

**Issue by tommattgeorge** [B-Lang-org/bsc#564]
I am using minspec: https://github.com/minispec-hdl/minispec to compile something on a private repo: https://github.com/tommattgeorge/ooo

I initially saw compiler warnings, and I edited the code to get rid of them. Then I received this error:

error: _@%@_ Please report this failure to the BSC developers, by opening a ticket
in the issue database: https://github.com/B-Lang-org/bsc/issues
The following internal error message should be included in your
correspondence along with any other relevant details:
Bluespec Compiler, version 2021.07 (build 4cac6eb)
BinData.readShared: invalid tag 95

I can give access to my private repo (it has some files that were part of a school assignment which was copyrighted by the instructors, I can ask them about it if it is too inconvenient by keeping it private).

**Comment by quark17** [comment]
This error occurs when BSC is trying to read in one of its generated files (`.bo` or `.ba`) but the contents of the file don't match the expected format.  This can either be because the contents were corrupted or because the file was generated by a different version of BSC, that uses a different format.  Usually BSC checks the header of the file, to determine if the same format was used, and BSC would give you an error about the mismatch and tell you to re-compile; but there could be a bug (that newer BSC needs to look for a newer header) and so that may be why you get the internal error instead of a nicer message.

There are two situations that are likely:

(1) You were using an older version of BSC and then you updated to a newer version of BSC, but still had files that were generated from the older version.  If that's the case, you need to wipe clean the previously generated files and re-compile.

(2) Your were given files that were previously compiled with BSC.  For example, if the assignment files from the instructor came pre-compiled.  If that's the case, you need to change to the same version of BSC that was used to compile those files.  (Or re-compile those files using your BSC version.)
